name: SSH Server Deploy
on: 
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Debug CI key fingerprint
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci
          ssh-keygen -lf ~/.ssh/id_ci
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Client Id Replacement
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "'clientIdHIDDEN'"
          replace: ${{ secrets.CLIENT_ID }}
          regex: false
      - name: Token Tina Replacement
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "'tokenTinaHIDDEN'"
          replace: ${{ secrets.TOKEN_TINA }}
          regex: false
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          port: '65002'
          username: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: ./dist
          scp_target: ./public_html
          before_script: |
            df -h
          after_script: |
            ls
            cp -r public_html/dist/* public_html/
