on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        with:
            path: . # The root location of your Astro project inside the repository. (optional)
            node-version: 16 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
            package-manager: npm # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
            resolve-dep-from-path: false # If the dependency file should be resolved from the root location of your Astro project. Defaults to `true`. (optional)

  deployment_job:
    runs-on: ubuntu-latest
    name: Deployment Job
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    - name: SSH
      uses: ErenKrt/ssh-push@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        source: "dist/"
        port: 65002
        #exclude: |
        #  *.exe
        #scripts: |
        #  cd /home/eren/test && unzip myZipname.zip && rm -r *.zip
        #  cat /home/eren/test/index.js
        #zipname: "myZipname.zip"
        #outdir: "/home/eren/test"